cookbookManager.import('oliverpool',
{
    "cake-aux-raisins": {"name":"Cake aux raisins","duration":{"value":60,"unit":"min"},"recipe":{"duration":{"value":50,"unit":"min"},"container":{"ingredients":[{"ingredients":[{"ingredients":[{"of":"Raisins secs","select":""},{"of":"Rhum","select":""}],"duration":{"value":"1","unit":"nuit"},"container":"Verre","description":"Laisser les raisins s'imbiber"}],"container":{"ingredients":[{"quantity":{"value":"1","unit":"pot"},"of":"Crème fraiche","select":""},{"quantity":{"value":"1","unit":"pot"},"of":"Farine","select":""},{"quantity":{"value":"1","unit":"pot"},"of":"Sucre","select":""},{"quantity":"2","of":"Oeufs","select":""}],"container":"Bol","description":"Mélanger les ingrédients"},"description":"Rajouter les raisins"}],"container":"Moule à Cake","description":"Verser le tout"},"description":"Mettre au four"}},
    "meringues": {"name":"Meringues","duration":{"value":60,"unit":"min"},"recipe":{"duration":{"value":50,"unit":"min"},"container":{"ingredients":[{"ingredients":[{"of":"sucre","quantity":{"value":60,"unit":"g"}}],"description":"Mélanger le sucre avec les blancs","container":{"ingredients":[{"quantity":1,"of":"oeuf","select":"seulement le blanc"}],"description":"Battre les blancs en neige","container":"Bol"}}],"description":"Faire des petits tas","container":"Plaque beurrée"},"description":"Mettre au four"}},
});

cookbookManager.import('eclairs',
{
    "pate-a-choux": {"name":"Pâte à choux","recipe":{"duration":{"value":"25","unit":"min"},"description":"Cuire au four (180°C)","container":{"ingredients":[{"ingredients":[{"quantity":"3","of":"Oeuf","select":""}],"description":"Ajouter les oeufs un à un en remuant jusqu'à ce que chaque oeuf soit incorporé","container":{"description":"Arrêter le feu, laisser tiédir","container":{"description":"Mélanger à la cuillère en bois quelques minutes, jusqu'à l'obtention d'une masse compacte qui se détache de la paroi","container":{"ingredients":[{"quantity":{"value":"100","unit":"g"},"of":"Farine","select":""}],"description":"Ajouter en une seule fois la farine","container":{"container":"Casserole","description":"Chauffer à feu moyen, en remuant","ingredients":[{"quantity":{"unit":"cl","value":"15"},"of":"Eau","select":""},{"quantity":{"value":"1","unit":"pincée"},"of":"Sel","select":""},{"quantity":{"unit":"g","value":"60"},"of":"Beurre","select":""},{"quantity":{"value":"1","unit":"càc"},"of":"Sucre","select":""}]}}}}}],"description":"A l'aide d'une poche à douille, déposer des petits tas","container":"Plaque beurrée"}},"serving":{"value":"8","unit":"éclairs"}},
    "creme-au-chocolat": {"name":"Crème au chocolat","recipe":{"description":"Arrêter le feu et laisser refroidir","container":{"description":"Laisser cuire, en remuant, quelques minutes jusqu'à épaississement","container":{"description":"Porter à légère ébullition sans cesser de remuer","container":{"ingredients":[{"ingredients":[{"quantity":{"unit":"g","value":"30"},"of":"Fécule","select":"de maïs"}],"description":"Incorporer la fécule","container":{"container":"Saladier (résistant à la chaleur)","description":"Battre jusqu'à ce que le mélange blanchisse","ingredients":[{"of":"Sucre","select":"","quantity":{"value":"70","unit":"g"}},{"quantity":{"unit":"jaunes","value":"3"},"of":"Oeufs","select":""}]}}],"description":"Verser doucement le lait chocolaté dans le saladier en le fouettant, puis reverser cette préparation dans la casserole","container":{"ingredients":[{"quantity":{"unit":"cl","value":"40"},"of":"Lait","select":"entier"},{"quantity":{"unit":"g","value":"100"},"of":"Chocolat noir dessert","select":"cassé en morceaux"}],"description":"Mélanger à feu moyen jusqu'à la disparition des morceaux","container":"Casserole"}}}}},"serving":{"value":"8","unit":"éclairs"}},
    "glacage": {"name":"Glaçage","recipe":{"container":"Casserole","description":"Faire fondre à feu doux","ingredients":[{"quantity":{"unit":"g","value":"30"},"of":"Beurre","select":""},{"quantity":{"value":"100","unit":"g"},"of":"Chocolat noir dessert","select":""},{"quantity":{"value":"2","unit":"càs"},"of":"Eau","select":""}]},"serving":{"value":"8","unit":"éclairs"}},
});